version: 2

models:
  - name: brand_asin
    columns:
      - name: key
        tests:
          - unique
  - name: category
    columns:
      - name: channel_product_id
        tests:
          - unique