select
ACCOUNT_KEY,
REGION,
MARKETPLACE_KEY,
BRAND,
date_trunc(month,date_day) as report_month,
asin,
SKU,
original_currency,
internal_sku_category,
sum(CAST(ledger_gross_sales AS NUMERIC(18,2))) AS ledger_gross_sales,
sum(CAST(canada_tax_on_gross_sales AS NUMERIC(18,2))) AS canada_tax_on_gross_sales,
sum(CAST(EARNED_GROSS_SALES AS NUMERIC(18,2))) AS EARNED_GROSS_SALES,
sum(CAST(ledger_gift_wrap AS NUMERIC(18,2))) AS ledger_gift_wrap,
sum(CAST(ledger_reimbursed_product AS NUMERIC(18,2))) AS ledger_reimbursed_product,
sum(CAST(ledger_REFUND_COMMISSION AS NUMERIC(18,2))) AS ledger_REFUND_COMMISSION,
sum(CAST(ledger_REFUNDED_REFERRAL_FEES AS NUMERIC(18,2))) AS ledger_REFUNDED_REFERRAL_FEES,
sum(CAST(ledger_REIMBURSED_SHIPPING AS NUMERIC(18,2))) AS ledger_REIMBURSED_SHIPPING,
sum(CAST(ledger_REFUND_PROMOTION AS NUMERIC(18,2))) AS ledger_REFUND_PROMOTION,
sum(CAST(ledger_REFUND_SHIPPING_CHARGEBACK AS NUMERIC(18,2))) AS ledger_REFUND_SHIPPING_CHARGEBACK,
sum(CAST(ledger_GOODWILL AS NUMERIC(18,2))) AS ledger_GOODWILL,
sum(CAST(ledger_REVERSAL_REIMBURSED AS NUMERIC(18,2))) AS ledger_REVERSAL_REIMBURSED,
sum(CAST(ledger_GIFT_WRAP_CHARGEBACK AS NUMERIC(18,2))) AS ledger_GIFT_WRAP_CHARGEBACK,
sum(CAST(ledger_shipping AS NUMERIC(18,2))) AS ledger_shipping,
sum(CAST(ledger_SHIPPING_CHARGEBACK AS NUMERIC(18,2))) AS ledger_SHIPPING_CHARGEBACK,
sum(CAST(ledger_fba_storage_fee AS NUMERIC(18,2))) AS ledger_fba_storage_fee,
sum(CAST(ledger_FBA_INVENTORY_PLACEMENT_SERVICE AS NUMERIC(18,2))) AS ledger_FBA_INVENTORY_PLACEMENT_SERVICE,
sum(CAST(ledger_WAREHOUSE_DAMAGE AS NUMERIC(18,2))) AS ledger_WAREHOUSE_DAMAGE,
sum(CAST(ledger_WAREHOUSE_LOST_MANUAL AS NUMERIC(18,2))) AS ledger_WAREHOUSE_LOST_MANUAL,
sum(CAST(ledger_FBA_PER_UNIT_FULFILMENT_FEE AS NUMERIC(18,2))) AS ledger_FBA_PER_UNIT_FULFILMENT_FEE,
sum(CAST(ledger_disposal_complete AS NUMERIC(18,2))) AS ledger_disposal_complete,
sum(CAST(ledger_removal_complete AS NUMERIC(18,2))) AS ledger_removal_complete,
sum(CAST(ledger_referral_fee AS NUMERIC(18,2))) AS ledger_referral_fee,
sum(CAST(ledger_promotion AS NUMERIC(18,2))) AS ledger_promotion,
sum(CAST(ledger_tax_principal AS NUMERIC(18,2))) AS ledger_tax_principal,
sum(CAST(ledger_tax_shipping AS NUMERIC(18,2))) AS ledger_tax_shipping,
sum(CAST(ledger_tax_reimbursed AS NUMERIC(18,2))) AS ledger_tax_reimbursed,
sum(CAST(ledger_tax_other AS NUMERIC(18,2))) AS ledger_tax_other,
sum(CAST(ledger_other_amount AS NUMERIC(18,2))) AS ledger_other_amount,
sum(CAST(other_amount_spot_only AS NUMERIC(18,2))) AS other_amount_spot_only,
sum(CAST(ledger_restocking_fee AS NUMERIC(18,2))) AS ledger_restocking_fee,
sum(CAST(ledger_brandhut_commission AS NUMERIC(18,2))) AS ledger_brandhut_commission,
sum(CAST(EARNED_BRANDHUT_COMMISSION AS NUMERIC(18,2))) AS EARNED_BRANDHUT_COMMISSION,
sum(CAST(orders AS NUMERIC(18,2))) AS orders,
sum(CAST(ledger_units_sold AS NUMERIC(18,2))) AS ledger_units_sold,
sum(CAST(ledger_units_returned AS NUMERIC(18,2))) AS ledger_units_returned,
sum(CAST(net_units_sold AS NUMERIC(18,2))) AS net_units_sold
from {{ref('int_finance__ledger_cleaned')}}
group by all
